// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"lockstep-core/src/config"
	"lockstep-core/src/logic"
	"lockstep-core/src/logic/room"
	"lockstep-core/src/server"
)

// Injectors from wire.go:

// InitializeApplication 初始化整个应用程序
// Wire 会自动生成这个函数的实现
func InitializeApplication() (*server.HTTPHandlers, error) {
	roomManager := room.NewRoomManager()
	defaultPlayerSessionHandler := logic.NewDefaultPlayerSessionHandler()
	serverConfig, err := config.NewDefaultConfig()
	if err != nil {
		return nil, err
	}
	webTransportServer := server.NewWebTransportServer(serverConfig)
	httpHandlers := server.NewHTTPHandlers(roomManager, defaultPlayerSessionHandler, webTransportServer)
	return httpHandlers, nil
}
