// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.32.0--rc1
// source: session_req.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 在长连接Session过程中，用户的所有可能请求
// 因为客户端发送的消息会被统一的后端ws handler解析
// 再根据后端room的状态进行分支处理
type SessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// oneof 确保一个 Request 消息实例中，只有一个字段能被设置
	//
	// Types that are assignable to Payload:
	//
	//	*SessionRequest_InLobby
	//	*SessionRequest_ToPreparing
	//	*SessionRequest_Ready
	//	*SessionRequest_ToInLobby
	//	*SessionRequest_Loaded
	//	*SessionRequest_InGameFrames
	//	*SessionRequest_Other
	//	*SessionRequest_EndGame
	//	*SessionRequest_ToPostGame
	Payload isSessionRequest_Payload `protobuf_oneof:"payload"`
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_req_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{0}
}

func (m *SessionRequest) GetPayload() isSessionRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *SessionRequest) GetInLobby() *RequestInLobby {
	if x, ok := x.GetPayload().(*SessionRequest_InLobby); ok {
		return x.InLobby
	}
	return nil
}

func (x *SessionRequest) GetToPreparing() *RequestToPreparing {
	if x, ok := x.GetPayload().(*SessionRequest_ToPreparing); ok {
		return x.ToPreparing
	}
	return nil
}

func (x *SessionRequest) GetReady() *RequestReady {
	if x, ok := x.GetPayload().(*SessionRequest_Ready); ok {
		return x.Ready
	}
	return nil
}

func (x *SessionRequest) GetToInLobby() *RequestToInLobby {
	if x, ok := x.GetPayload().(*SessionRequest_ToInLobby); ok {
		return x.ToInLobby
	}
	return nil
}

func (x *SessionRequest) GetLoaded() *RequestLoaded {
	if x, ok := x.GetPayload().(*SessionRequest_Loaded); ok {
		return x.Loaded
	}
	return nil
}

func (x *SessionRequest) GetInGameFrames() *RequestInGameFrames {
	if x, ok := x.GetPayload().(*SessionRequest_InGameFrames); ok {
		return x.InGameFrames
	}
	return nil
}

func (x *SessionRequest) GetOther() *RequestOther {
	if x, ok := x.GetPayload().(*SessionRequest_Other); ok {
		return x.Other
	}
	return nil
}

func (x *SessionRequest) GetEndGame() *RequestEndGame {
	if x, ok := x.GetPayload().(*SessionRequest_EndGame); ok {
		return x.EndGame
	}
	return nil
}

func (x *SessionRequest) GetToPostGame() *RequestToPostGame {
	if x, ok := x.GetPayload().(*SessionRequest_ToPostGame); ok {
		return x.ToPostGame
	}
	return nil
}

type isSessionRequest_Payload interface {
	isSessionRequest_Payload()
}

type SessionRequest_InLobby struct {
	// STAGE_InLobby
	InLobby *RequestInLobby `protobuf:"bytes,1,opt,name=in_lobby,json=inLobby,proto3,oneof"`
}

type SessionRequest_ToPreparing struct {
	ToPreparing *RequestToPreparing `protobuf:"bytes,2,opt,name=to_preparing,json=toPreparing,proto3,oneof"`
}

type SessionRequest_Ready struct {
	// STAGE_Preparing
	Ready *RequestReady `protobuf:"bytes,3,opt,name=ready,proto3,oneof"`
}

type SessionRequest_ToInLobby struct {
	ToInLobby *RequestToInLobby `protobuf:"bytes,4,opt,name=to_in_lobby,json=toInLobby,proto3,oneof"`
}

type SessionRequest_Loaded struct {
	// STAGE_Loading
	Loaded *RequestLoaded `protobuf:"bytes,5,opt,name=loaded,proto3,oneof"`
}

type SessionRequest_InGameFrames struct {
	// STAGE_InGame
	InGameFrames *RequestInGameFrames `protobuf:"bytes,6,opt,name=in_game_frames,json=inGameFrames,proto3,oneof"`
}

type SessionRequest_Other struct {
	Other *RequestOther `protobuf:"bytes,7,opt,name=other,proto3,oneof"`
}

type SessionRequest_EndGame struct {
	EndGame *RequestEndGame `protobuf:"bytes,8,opt,name=end_game,json=endGame,proto3,oneof"`
}

type SessionRequest_ToPostGame struct {
	// STAGE_PostGame
	ToPostGame *RequestToPostGame `protobuf:"bytes,9,opt,name=to_post_game,json=toPostGame,proto3,oneof"`
}

func (*SessionRequest_InLobby) isSessionRequest_Payload() {}

func (*SessionRequest_ToPreparing) isSessionRequest_Payload() {}

func (*SessionRequest_Ready) isSessionRequest_Payload() {}

func (*SessionRequest_ToInLobby) isSessionRequest_Payload() {}

func (*SessionRequest_Loaded) isSessionRequest_Payload() {}

func (*SessionRequest_InGameFrames) isSessionRequest_Payload() {}

func (*SessionRequest_Other) isSessionRequest_Payload() {}

func (*SessionRequest_EndGame) isSessionRequest_Payload() {}

func (*SessionRequest_ToPostGame) isSessionRequest_Payload() {}

// RequestInLobby 大厅中的请求，透传给游戏世界
type RequestInLobby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 携带的bytes，框架将直接传给游戏世界处理
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RequestInLobby) Reset() {
	*x = RequestInLobby{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_req_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestInLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInLobby) ProtoMessage() {}

func (x *RequestInLobby) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInLobby.ProtoReflect.Descriptor instead.
func (*RequestInLobby) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{1}
}

func (x *RequestInLobby) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RequestToPreparing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 携带的bytes，框架将直接传给游戏世界处理
	// 例如关卡数据等
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RequestToPreparing) Reset() {
	*x = RequestToPreparing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_req_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestToPreparing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestToPreparing) ProtoMessage() {}

func (x *RequestToPreparing) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestToPreparing.ProtoReflect.Descriptor instead.
func (*RequestToPreparing) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{2}
}

func (x *RequestToPreparing) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Ready 表示某个客户端在选卡界面切换准备就绪
type RequestReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsReady bool `protobuf:"varint,1,opt,name=isReady,proto3" json:"isReady,omitempty"`
}

func (x *RequestReady) Reset() {
	*x = RequestReady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_req_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestReady) ProtoMessage() {}

func (x *RequestReady) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestReady.ProtoReflect.Descriptor instead.
func (*RequestReady) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{3}
}

func (x *RequestReady) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

// 请求返回大厅
type RequestToInLobby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 携带的bytes，框架将直接传给游戏世界处理
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RequestToInLobby) Reset() {
	*x = RequestToInLobby{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_req_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestToInLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestToInLobby) ProtoMessage() {}

func (x *RequestToInLobby) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestToInLobby.ProtoReflect.Descriptor instead.
func (*RequestToInLobby) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{4}
}

func (x *RequestToInLobby) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Loading 加载阶段
type RequestLoaded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsLoaded bool `protobuf:"varint,1,opt,name=isLoaded,proto3" json:"isLoaded,omitempty"`
}

func (x *RequestLoaded) Reset() {
	*x = RequestLoaded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_req_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestLoaded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLoaded) ProtoMessage() {}

func (x *RequestLoaded) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLoaded.ProtoReflect.Descriptor instead.
func (*RequestLoaded) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{5}
}

func (x *RequestLoaded) GetIsLoaded() bool {
	if x != nil {
		return x.IsLoaded
	}
	return false
}

// RequestBlank 用于心跳并携带具体用户请求
type RequestInGameFrames struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 本数据包所作操作是为了步进到的帧ID
	FrameId uint32 `protobuf:"varint,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	// 客户端确认服务端上一次的“步进到”的帧ID
	AckFrameId uint32 `protobuf:"varint,2,opt,name=ack_frame_id,json=ackFrameId,proto3" json:"ack_frame_id,omitempty"`
	// 携带的bytes，框架将直接传给游戏世界处理
	// 如果为空，则说明为没有操作空白帧
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *RequestInGameFrames) Reset() {
	*x = RequestInGameFrames{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_req_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestInGameFrames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInGameFrames) ProtoMessage() {}

func (x *RequestInGameFrames) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInGameFrames.ProtoReflect.Descriptor instead.
func (*RequestInGameFrames) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{6}
}

func (x *RequestInGameFrames) GetFrameId() uint32 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *RequestInGameFrames) GetAckFrameId() uint32 {
	if x != nil {
		return x.AckFrameId
	}
	return 0
}

func (x *RequestInGameFrames) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RequestEndGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏结束状态码
	StatusCode uint32 `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	// 携带的bytes，框架将直接传给游戏世界处理
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *RequestEndGame) Reset() {
	*x = RequestEndGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_req_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestEndGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEndGame) ProtoMessage() {}

func (x *RequestEndGame) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEndGame.ProtoReflect.Descriptor instead.
func (*RequestEndGame) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{7}
}

func (x *RequestEndGame) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RequestEndGame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// PostGame 游戏结束后
type RequestToPostGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 携带的bytes，框架将直接传给游戏世界处理
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *RequestToPostGame) Reset() {
	*x = RequestToPostGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_req_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestToPostGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestToPostGame) ProtoMessage() {}

func (x *RequestToPostGame) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestToPostGame.ProtoReflect.Descriptor instead.
func (*RequestToPostGame) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{8}
}

func (x *RequestToPostGame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 请求，例如聊天信息
type RequestOther struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 携带的bytes，框架将直接传给游戏世界处理
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RequestOther) Reset() {
	*x = RequestOther{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_req_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestOther) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOther) ProtoMessage() {}

func (x *RequestOther) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOther.ProtoReflect.Descriptor instead.
func (*RequestOther) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{9}
}

func (x *RequestOther) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_session_req_proto protoreflect.FileDescriptor

var file_session_req_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0xa5, 0x04,
	0x0a, 0x0e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x35, 0x0a, 0x08, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x48, 0x00, 0x52, 0x07,
	0x69, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x41, 0x0a, 0x0c, 0x74, 0x6f, 0x5f, 0x70, 0x72,
	0x65, 0x70, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x54, 0x6f, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x0b, 0x74,
	0x6f, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x2e, 0x0a, 0x05, 0x72, 0x65,
	0x61, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x61, 0x64,
	0x79, 0x48, 0x00, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x3c, 0x0a, 0x0b, 0x74, 0x6f,
	0x5f, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x54, 0x6f, 0x49, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x48, 0x00, 0x52, 0x09, 0x74,
	0x6f, 0x49, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x31, 0x0a, 0x06, 0x6c, 0x6f, 0x61, 0x64,
	0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x6f, 0x61, 0x64, 0x65,
	0x64, 0x48, 0x00, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x12, 0x45, 0x0a, 0x0e, 0x69,
	0x6e, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x73, 0x48, 0x00, 0x52, 0x0c, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x73, 0x12, 0x2e, 0x0a, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x48, 0x00, 0x52, 0x05, 0x6f, 0x74, 0x68,
	0x65, 0x72, 0x12, 0x35, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x00,
	0x52, 0x07, 0x65, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x3f, 0x0a, 0x0c, 0x74, 0x6f, 0x5f,
	0x70, 0x6f, 0x73, 0x74, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x54, 0x6f, 0x50, 0x6f, 0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x0a,
	0x74, 0x6f, 0x50, 0x6f, 0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x24, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x28, 0x0a, 0x12, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x6f, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x69, 0x6e,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x28, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x61, 0x64, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x22,
	0x26, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x6f, 0x49, 0x6e, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2b, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x4c, 0x6f,
	0x61, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4c, 0x6f,
	0x61, 0x64, 0x65, 0x64, 0x22, 0x74, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x6e, 0x47, 0x61, 0x6d, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x66,
	0x72, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x66,
	0x72, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x61, 0x63, 0x6b, 0x5f, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x61, 0x63,
	0x6b, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01,
	0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x52, 0x0a, 0x0e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x35,
	0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x6f, 0x50, 0x6f, 0x73, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x4f, 0x74, 0x68, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_session_req_proto_rawDescOnce sync.Once
	file_session_req_proto_rawDescData = file_session_req_proto_rawDesc
)

func file_session_req_proto_rawDescGZIP() []byte {
	file_session_req_proto_rawDescOnce.Do(func() {
		file_session_req_proto_rawDescData = protoimpl.X.CompressGZIP(file_session_req_proto_rawDescData)
	})
	return file_session_req_proto_rawDescData
}

var file_session_req_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_session_req_proto_goTypes = []interface{}{
	(*SessionRequest)(nil),      // 0: messages.SessionRequest
	(*RequestInLobby)(nil),      // 1: messages.RequestInLobby
	(*RequestToPreparing)(nil),  // 2: messages.RequestToPreparing
	(*RequestReady)(nil),        // 3: messages.RequestReady
	(*RequestToInLobby)(nil),    // 4: messages.RequestToInLobby
	(*RequestLoaded)(nil),       // 5: messages.RequestLoaded
	(*RequestInGameFrames)(nil), // 6: messages.RequestInGameFrames
	(*RequestEndGame)(nil),      // 7: messages.RequestEndGame
	(*RequestToPostGame)(nil),   // 8: messages.RequestToPostGame
	(*RequestOther)(nil),        // 9: messages.RequestOther
}
var file_session_req_proto_depIdxs = []int32{
	1, // 0: messages.SessionRequest.in_lobby:type_name -> messages.RequestInLobby
	2, // 1: messages.SessionRequest.to_preparing:type_name -> messages.RequestToPreparing
	3, // 2: messages.SessionRequest.ready:type_name -> messages.RequestReady
	4, // 3: messages.SessionRequest.to_in_lobby:type_name -> messages.RequestToInLobby
	5, // 4: messages.SessionRequest.loaded:type_name -> messages.RequestLoaded
	6, // 5: messages.SessionRequest.in_game_frames:type_name -> messages.RequestInGameFrames
	9, // 6: messages.SessionRequest.other:type_name -> messages.RequestOther
	7, // 7: messages.SessionRequest.end_game:type_name -> messages.RequestEndGame
	8, // 8: messages.SessionRequest.to_post_game:type_name -> messages.RequestToPostGame
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_session_req_proto_init() }
func file_session_req_proto_init() {
	if File_session_req_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_session_req_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_session_req_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestInLobby); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_session_req_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestToPreparing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_session_req_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestReady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_session_req_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestToInLobby); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_session_req_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestLoaded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_session_req_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestInGameFrames); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_session_req_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestEndGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_session_req_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestToPostGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_session_req_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestOther); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_session_req_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SessionRequest_InLobby)(nil),
		(*SessionRequest_ToPreparing)(nil),
		(*SessionRequest_Ready)(nil),
		(*SessionRequest_ToInLobby)(nil),
		(*SessionRequest_Loaded)(nil),
		(*SessionRequest_InGameFrames)(nil),
		(*SessionRequest_Other)(nil),
		(*SessionRequest_EndGame)(nil),
		(*SessionRequest_ToPostGame)(nil),
	}
	file_session_req_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_session_req_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_session_req_proto_msgTypes[8].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_session_req_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_session_req_proto_goTypes,
		DependencyIndexes: file_session_req_proto_depIdxs,
		MessageInfos:      file_session_req_proto_msgTypes,
	}.Build()
	File_session_req_proto = out.File
	file_session_req_proto_rawDesc = nil
	file_session_req_proto_goTypes = nil
	file_session_req_proto_depIdxs = nil
}
