// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: session_req.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 在长连接Session过程中，用户的所有可能请求
// 因为客户端发送的消息会被统一的后端ws handler解析
// 再根据后端room的状态进行分支处理
type SessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// oneof 确保一个 Request 消息实例中，只有一个字段能被设置
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*SessionRequest_InLobby
	//	*SessionRequest_ToPreparing
	//	*SessionRequest_Ready
	//	*SessionRequest_ToInLobby
	//	*SessionRequest_Loaded
	//	*SessionRequest_InGameFrames
	//	*SessionRequest_Other
	//	*SessionRequest_EndGame
	//	*SessionRequest_PostGameData
	Payload       isSessionRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_session_req_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{0}
}

func (x *SessionRequest) GetPayload() isSessionRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SessionRequest) GetInLobby() *RequestInLobby {
	if x != nil {
		if x, ok := x.Payload.(*SessionRequest_InLobby); ok {
			return x.InLobby
		}
	}
	return nil
}

func (x *SessionRequest) GetToPreparing() *RequestToPreparing {
	if x != nil {
		if x, ok := x.Payload.(*SessionRequest_ToPreparing); ok {
			return x.ToPreparing
		}
	}
	return nil
}

func (x *SessionRequest) GetReady() *RequestReady {
	if x != nil {
		if x, ok := x.Payload.(*SessionRequest_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *SessionRequest) GetToInLobby() *RequestToInLobby {
	if x != nil {
		if x, ok := x.Payload.(*SessionRequest_ToInLobby); ok {
			return x.ToInLobby
		}
	}
	return nil
}

func (x *SessionRequest) GetLoaded() *RequestLoaded {
	if x != nil {
		if x, ok := x.Payload.(*SessionRequest_Loaded); ok {
			return x.Loaded
		}
	}
	return nil
}

func (x *SessionRequest) GetInGameFrames() *RequestInGameFrames {
	if x != nil {
		if x, ok := x.Payload.(*SessionRequest_InGameFrames); ok {
			return x.InGameFrames
		}
	}
	return nil
}

func (x *SessionRequest) GetOther() *RequestOther {
	if x != nil {
		if x, ok := x.Payload.(*SessionRequest_Other); ok {
			return x.Other
		}
	}
	return nil
}

func (x *SessionRequest) GetEndGame() *RequestEndGame {
	if x != nil {
		if x, ok := x.Payload.(*SessionRequest_EndGame); ok {
			return x.EndGame
		}
	}
	return nil
}

func (x *SessionRequest) GetPostGameData() *RequestPostGameData {
	if x != nil {
		if x, ok := x.Payload.(*SessionRequest_PostGameData); ok {
			return x.PostGameData
		}
	}
	return nil
}

type isSessionRequest_Payload interface {
	isSessionRequest_Payload()
}

type SessionRequest_InLobby struct {
	// STAGE_InLobby
	InLobby *RequestInLobby `protobuf:"bytes,1,opt,name=in_lobby,json=inLobby,proto3,oneof"`
}

type SessionRequest_ToPreparing struct {
	ToPreparing *RequestToPreparing `protobuf:"bytes,2,opt,name=to_preparing,json=toPreparing,proto3,oneof"`
}

type SessionRequest_Ready struct {
	// STAGE_Preparing
	Ready *RequestReady `protobuf:"bytes,3,opt,name=ready,proto3,oneof"`
}

type SessionRequest_ToInLobby struct {
	ToInLobby *RequestToInLobby `protobuf:"bytes,4,opt,name=to_in_lobby,json=toInLobby,proto3,oneof"`
}

type SessionRequest_Loaded struct {
	// STAGE_Loading
	Loaded *RequestLoaded `protobuf:"bytes,5,opt,name=loaded,proto3,oneof"`
}

type SessionRequest_InGameFrames struct {
	// STAGE_InGame
	InGameFrames *RequestInGameFrames `protobuf:"bytes,6,opt,name=in_game_frames,json=inGameFrames,proto3,oneof"`
}

type SessionRequest_Other struct {
	Other *RequestOther `protobuf:"bytes,7,opt,name=other,proto3,oneof"`
}

type SessionRequest_EndGame struct {
	EndGame *RequestEndGame `protobuf:"bytes,8,opt,name=end_game,json=endGame,proto3,oneof"`
}

type SessionRequest_PostGameData struct {
	// STAGE_PostGame
	PostGameData *RequestPostGameData `protobuf:"bytes,9,opt,name=post_game_data,json=postGameData,proto3,oneof"`
}

func (*SessionRequest_InLobby) isSessionRequest_Payload() {}

func (*SessionRequest_ToPreparing) isSessionRequest_Payload() {}

func (*SessionRequest_Ready) isSessionRequest_Payload() {}

func (*SessionRequest_ToInLobby) isSessionRequest_Payload() {}

func (*SessionRequest_Loaded) isSessionRequest_Payload() {}

func (*SessionRequest_InGameFrames) isSessionRequest_Payload() {}

func (*SessionRequest_Other) isSessionRequest_Payload() {}

func (*SessionRequest_EndGame) isSessionRequest_Payload() {}

func (*SessionRequest_PostGameData) isSessionRequest_Payload() {}

// RequestInLobby 大厅中的请求，透传给游戏世界
type RequestInLobby struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 携带的bytes，框架将直接传给游戏世界处理
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInLobby) Reset() {
	*x = RequestInLobby{}
	mi := &file_session_req_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInLobby) ProtoMessage() {}

func (x *RequestInLobby) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInLobby.ProtoReflect.Descriptor instead.
func (*RequestInLobby) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{1}
}

func (x *RequestInLobby) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RequestToPreparing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 携带的bytes，框架将直接传给游戏世界处理
	// 例如关卡数据等
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestToPreparing) Reset() {
	*x = RequestToPreparing{}
	mi := &file_session_req_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestToPreparing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestToPreparing) ProtoMessage() {}

func (x *RequestToPreparing) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestToPreparing.ProtoReflect.Descriptor instead.
func (*RequestToPreparing) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{2}
}

func (x *RequestToPreparing) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Ready 表示某个客户端在选卡界面切换准备就绪
type RequestReady struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	IsReady bool                   `protobuf:"varint,1,opt,name=isReady,proto3" json:"isReady,omitempty"`
	// 携带的bytes，例如装备数据
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestReady) Reset() {
	*x = RequestReady{}
	mi := &file_session_req_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestReady) ProtoMessage() {}

func (x *RequestReady) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestReady.ProtoReflect.Descriptor instead.
func (*RequestReady) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{3}
}

func (x *RequestReady) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *RequestReady) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 请求返回大厅
type RequestToInLobby struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 携带的bytes，框架将直接传给游戏世界处理
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestToInLobby) Reset() {
	*x = RequestToInLobby{}
	mi := &file_session_req_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestToInLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestToInLobby) ProtoMessage() {}

func (x *RequestToInLobby) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestToInLobby.ProtoReflect.Descriptor instead.
func (*RequestToInLobby) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{4}
}

func (x *RequestToInLobby) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Loading 加载阶段
type RequestLoaded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLoaded      bool                   `protobuf:"varint,1,opt,name=isLoaded,proto3" json:"isLoaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestLoaded) Reset() {
	*x = RequestLoaded{}
	mi := &file_session_req_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestLoaded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLoaded) ProtoMessage() {}

func (x *RequestLoaded) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLoaded.ProtoReflect.Descriptor instead.
func (*RequestLoaded) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{5}
}

func (x *RequestLoaded) GetIsLoaded() bool {
	if x != nil {
		return x.IsLoaded
	}
	return false
}

// RequestBlank 用于心跳并携带具体用户请求
type RequestInGameFrames struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 本数据包所作操作是为了步进到的帧ID
	FrameId uint32 `protobuf:"varint,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	// 客户端确认服务端上一次的“步进到”的帧ID
	AckFrameId uint32 `protobuf:"varint,2,opt,name=ack_frame_id,json=ackFrameId,proto3" json:"ack_frame_id,omitempty"`
	// 携带的bytes，框架将直接传给游戏世界处理
	// 如果为空，则说明为没有操作空白帧
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInGameFrames) Reset() {
	*x = RequestInGameFrames{}
	mi := &file_session_req_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInGameFrames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInGameFrames) ProtoMessage() {}

func (x *RequestInGameFrames) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInGameFrames.ProtoReflect.Descriptor instead.
func (*RequestInGameFrames) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{6}
}

func (x *RequestInGameFrames) GetFrameId() uint32 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *RequestInGameFrames) GetAckFrameId() uint32 {
	if x != nil {
		return x.AckFrameId
	}
	return 0
}

func (x *RequestInGameFrames) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 申请结束游戏
// 如果同意则跳转到 PostGame 阶段
type RequestEndGame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 游戏结束状态码
	StatusCode uint32 `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	// 携带的bytes，框架将直接传给游戏世界处理
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEndGame) Reset() {
	*x = RequestEndGame{}
	mi := &file_session_req_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEndGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEndGame) ProtoMessage() {}

func (x *RequestEndGame) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEndGame.ProtoReflect.Descriptor instead.
func (*RequestEndGame) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{7}
}

func (x *RequestEndGame) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RequestEndGame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// PostGame 游戏结束后的数据
// 可能用于发送战绩数据等信息
type RequestPostGameData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 携带的bytes，框架将直接传给游戏世界处理
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPostGameData) Reset() {
	*x = RequestPostGameData{}
	mi := &file_session_req_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPostGameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPostGameData) ProtoMessage() {}

func (x *RequestPostGameData) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPostGameData.ProtoReflect.Descriptor instead.
func (*RequestPostGameData) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{8}
}

func (x *RequestPostGameData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 请求，例如聊天信息
type RequestOther struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 携带的bytes，框架将直接传给游戏世界处理
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOther) Reset() {
	*x = RequestOther{}
	mi := &file_session_req_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOther) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOther) ProtoMessage() {}

func (x *RequestOther) ProtoReflect() protoreflect.Message {
	mi := &file_session_req_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOther.ProtoReflect.Descriptor instead.
func (*RequestOther) Descriptor() ([]byte, []int) {
	return file_session_req_proto_rawDescGZIP(), []int{9}
}

func (x *RequestOther) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_session_req_proto protoreflect.FileDescriptor

const file_session_req_proto_rawDesc = "" +
	"\n" +
	"\x11session_req.proto\x12\bmessages\"\xab\x04\n" +
	"\x0eSessionRequest\x125\n" +
	"\bin_lobby\x18\x01 \x01(\v2\x18.messages.RequestInLobbyH\x00R\ainLobby\x12A\n" +
	"\fto_preparing\x18\x02 \x01(\v2\x1c.messages.RequestToPreparingH\x00R\vtoPreparing\x12.\n" +
	"\x05ready\x18\x03 \x01(\v2\x16.messages.RequestReadyH\x00R\x05ready\x12<\n" +
	"\vto_in_lobby\x18\x04 \x01(\v2\x1a.messages.RequestToInLobbyH\x00R\ttoInLobby\x121\n" +
	"\x06loaded\x18\x05 \x01(\v2\x17.messages.RequestLoadedH\x00R\x06loaded\x12E\n" +
	"\x0ein_game_frames\x18\x06 \x01(\v2\x1d.messages.RequestInGameFramesH\x00R\finGameFrames\x12.\n" +
	"\x05other\x18\a \x01(\v2\x16.messages.RequestOtherH\x00R\x05other\x125\n" +
	"\bend_game\x18\b \x01(\v2\x18.messages.RequestEndGameH\x00R\aendGame\x12E\n" +
	"\x0epost_game_data\x18\t \x01(\v2\x1d.messages.RequestPostGameDataH\x00R\fpostGameDataB\t\n" +
	"\apayload\"$\n" +
	"\x0eRequestInLobby\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"(\n" +
	"\x12RequestToPreparing\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"J\n" +
	"\fRequestReady\x12\x18\n" +
	"\aisReady\x18\x01 \x01(\bR\aisReady\x12\x17\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x88\x01\x01B\a\n" +
	"\x05_data\"&\n" +
	"\x10RequestToInLobby\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"+\n" +
	"\rRequestLoaded\x12\x1a\n" +
	"\bisLoaded\x18\x01 \x01(\bR\bisLoaded\"t\n" +
	"\x13RequestInGameFrames\x12\x19\n" +
	"\bframe_id\x18\x01 \x01(\rR\aframeId\x12 \n" +
	"\fack_frame_id\x18\x02 \x01(\rR\n" +
	"ackFrameId\x12\x17\n" +
	"\x04data\x18\x03 \x01(\fH\x00R\x04data\x88\x01\x01B\a\n" +
	"\x05_data\"R\n" +
	"\x0eRequestEndGame\x12\x1e\n" +
	"\n" +
	"StatusCode\x18\x01 \x01(\rR\n" +
	"StatusCode\x12\x17\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x88\x01\x01B\a\n" +
	"\x05_data\"7\n" +
	"\x13RequestPostGameData\x12\x17\n" +
	"\x04data\x18\x01 \x01(\fH\x00R\x04data\x88\x01\x01B\a\n" +
	"\x05_data\"\"\n" +
	"\fRequestOther\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04dataB\rZ\v./;messagesb\x06proto3"

var (
	file_session_req_proto_rawDescOnce sync.Once
	file_session_req_proto_rawDescData []byte
)

func file_session_req_proto_rawDescGZIP() []byte {
	file_session_req_proto_rawDescOnce.Do(func() {
		file_session_req_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_req_proto_rawDesc), len(file_session_req_proto_rawDesc)))
	})
	return file_session_req_proto_rawDescData
}

var file_session_req_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_session_req_proto_goTypes = []any{
	(*SessionRequest)(nil),      // 0: messages.SessionRequest
	(*RequestInLobby)(nil),      // 1: messages.RequestInLobby
	(*RequestToPreparing)(nil),  // 2: messages.RequestToPreparing
	(*RequestReady)(nil),        // 3: messages.RequestReady
	(*RequestToInLobby)(nil),    // 4: messages.RequestToInLobby
	(*RequestLoaded)(nil),       // 5: messages.RequestLoaded
	(*RequestInGameFrames)(nil), // 6: messages.RequestInGameFrames
	(*RequestEndGame)(nil),      // 7: messages.RequestEndGame
	(*RequestPostGameData)(nil), // 8: messages.RequestPostGameData
	(*RequestOther)(nil),        // 9: messages.RequestOther
}
var file_session_req_proto_depIdxs = []int32{
	1, // 0: messages.SessionRequest.in_lobby:type_name -> messages.RequestInLobby
	2, // 1: messages.SessionRequest.to_preparing:type_name -> messages.RequestToPreparing
	3, // 2: messages.SessionRequest.ready:type_name -> messages.RequestReady
	4, // 3: messages.SessionRequest.to_in_lobby:type_name -> messages.RequestToInLobby
	5, // 4: messages.SessionRequest.loaded:type_name -> messages.RequestLoaded
	6, // 5: messages.SessionRequest.in_game_frames:type_name -> messages.RequestInGameFrames
	9, // 6: messages.SessionRequest.other:type_name -> messages.RequestOther
	7, // 7: messages.SessionRequest.end_game:type_name -> messages.RequestEndGame
	8, // 8: messages.SessionRequest.post_game_data:type_name -> messages.RequestPostGameData
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_session_req_proto_init() }
func file_session_req_proto_init() {
	if File_session_req_proto != nil {
		return
	}
	file_session_req_proto_msgTypes[0].OneofWrappers = []any{
		(*SessionRequest_InLobby)(nil),
		(*SessionRequest_ToPreparing)(nil),
		(*SessionRequest_Ready)(nil),
		(*SessionRequest_ToInLobby)(nil),
		(*SessionRequest_Loaded)(nil),
		(*SessionRequest_InGameFrames)(nil),
		(*SessionRequest_Other)(nil),
		(*SessionRequest_EndGame)(nil),
		(*SessionRequest_PostGameData)(nil),
	}
	file_session_req_proto_msgTypes[3].OneofWrappers = []any{}
	file_session_req_proto_msgTypes[6].OneofWrappers = []any{}
	file_session_req_proto_msgTypes[7].OneofWrappers = []any{}
	file_session_req_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_req_proto_rawDesc), len(file_session_req_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_session_req_proto_goTypes,
		DependencyIndexes: file_session_req_proto_depIdxs,
		MessageInfos:      file_session_req_proto_msgTypes,
	}.Build()
	File_session_req_proto = out.File
	file_session_req_proto_goTypes = nil
	file_session_req_proto_depIdxs = nil
}
